# Generated by Django 6.0.6 on 2026-08-18 16:41

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Working', '0022_alter_appuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_xuat', models.DateField(default=datetime.date.today, verbose_name='Ngày xuất')),
                ('ma_hang', models.CharField(max_length=255, verbose_name='Mã hàng')),
                ('mau', models.CharField(max_length=255, verbose_name='Màu')),
                ('ten_vat_tu', models.CharField(max_length=255, verbose_name='Tên vật tư')),
                ('so_luong_kien', models.PositiveIntegerField(default=0, verbose_name='Số lượng kiện/cây')),
                ('so_luong_met', models.FloatField(default=0.0, verbose_name='Số lượng mét')),
                ('nguoi_nhan', models.CharField(max_length=255, verbose_name='Người nhận')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian nhập')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('nguoi_xuat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_issues', to='Working.appuser', verbose_name='Người xuất')),
            ],
            options={
                'verbose_name': 'Phiếu xuất nguyên liệu',
                'verbose_name_plural': 'Phiếu xuất nguyên liệu',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_nhap', models.DateField(default=datetime.date.today, verbose_name='Ngày nhập')),
                ('ma_hang', models.CharField(max_length=255, verbose_name='Mã hàng')),
                ('mau', models.CharField(max_length=255, verbose_name='Màu')),
                ('ten_vat_tu', models.CharField(max_length=255, verbose_name='Tên vật tư')),
                ('so_luong_kien', models.PositiveIntegerField(default=0, verbose_name='Số lượng kiện/cây')),
                ('so_luong_met', models.FloatField(default=0.0, verbose_name='Số lượng mét')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian nhập')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('nguoi_nhap', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_receipts', to='Working.appuser', verbose_name='Người nhập')),
            ],
            options={
                'verbose_name': 'Phiếu nhập nguyên liệu',
                'verbose_name_plural': 'Phiếu nhập nguyên liệu',
                'ordering': ['-created_at'],
            },
        ),
    ]
