# Generated by Django 6.0.6 on 2026-08-20 15:18

from django.db import migrations, models


def convert_id_to_name(apps, schema_editor):
    MaterialIssue = apps.get_model('Inventory', 'MaterialIssue')
    AppUser = apps.get_model('Working', 'AppUser')
    for issue in MaterialIssue.objects.all():
        val = str(issue.nguoi_nhan).strip()
        if val.isdigit():
            user = AppUser.objects.filter(id=int(val)).first()
            if user:
                issue.nguoi_nhan = user.name
                issue.save()

class Migration(migrations.Migration):

    dependencies = [
        ('Working', '0022_alter_appuser_role'),
        ('Inventory', '0003_alter_materialissue_nguoi_nhan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialissue',
            name='nguoi_nhan',
            field=models.CharField(max_length=255, verbose_name='Người nhận'),
        ),
        migrations.RunPython(convert_id_to_name, reverse_code=migrations.RunPython.noop),
    ]
