# Generated by Django 6.0.6 on 2026-08-20 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0004_alter_materialissue_nguoi_nhan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materialreceipt',
            old_name='so_luong_met',
            new_name='so_luong',
        ),
        migrations.AlterField(
            model_name='materialreceipt',
            name='so_luong',
            field=models.FloatField(default=0.0, verbose_name='Số lượng'),
        ),
        migrations.AddField(
            model_name='materialreceipt',
            name='don_vi',
            field=models.CharField(choices=[('m', 'm'), ('y', 'y'), ('chiếc', 'chiếc')], default='m', max_length=20, verbose_name='Đơn vị'),
        ),
        migrations.RenameField(
            model_name='materialissue',
            old_name='so_luong_met',
            new_name='so_luong',
        ),
        migrations.AlterField(
            model_name='materialissue',
            name='so_luong',
            field=models.FloatField(default=0.0, verbose_name='Số lượng'),
        ),
        migrations.AddField(
            model_name='materialissue',
            name='don_vi',
            field=models.CharField(choices=[('m', 'm'), ('y', 'y'), ('chiếc', 'chiếc')], default='m', max_length=20, verbose_name='Đơn vị'),
        ),
    ]
