# Generated by Django 6.0.6 on 2026-07-12 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Họ tên')),
                ('account', models.CharField(max_length=150, unique=True, verbose_name='Tài khoản')),
                ('password', models.CharField(max_length=255, verbose_name='Mật khẩu')),
            ],
            options={
                'verbose_name': 'Tài khoản người dùng',
                'verbose_name_plural': 'Tài khoản người dùng',
            },
        ),
        migrations.CreateModel(
            name='ProcessReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_hang', models.CharField(max_length=255, verbose_name='Mã hàng')),
                ('mau', models.CharField(max_length=255, verbose_name='Màu')),
                ('size', models.CharField(max_length=50, verbose_name='Cỡ')),
                ('nhan_btp', models.PositiveIntegerField(default=0, verbose_name='Nhận BTP')),
                ('vao_chuyen', models.PositiveIntegerField(default=0, verbose_name='Vào chuyền')),
                ('giua_chuyen', models.PositiveIntegerField(default=0, verbose_name='Giữa chuyền')),
                ('ra_chuyen', models.PositiveIntegerField(default=0, verbose_name='Ra chuyền')),
                ('thu_hoa', models.PositiveIntegerField(default=0, verbose_name='Thu hóa')),
                ('la_thanh_pham', models.PositiveIntegerField(default=0, verbose_name='Là thành phẩm')),
                ('kcs', models.PositiveIntegerField(default=0, verbose_name='KCS')),
                ('nhap_hoan_thien', models.PositiveIntegerField(default=0, verbose_name='Nhập hoàn thiện')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian nhập')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('nguoi_nhap', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='process_reports', to='Working.appuser', verbose_name='Người nhập')),
            ],
            options={
                'verbose_name': 'Báo cáo quy trình',
                'verbose_name_plural': 'Báo cáo quy trình',
                'ordering': ['-created_at'],
            },
        ),
    ]
