# Generated by Django 6.0.6 on 2026-08-03 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Working', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='processreport',
            name='to',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Tổ'),
        ),
    ]
