# Generated by Django 6.0.6 on 2026-08-03 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Working', '0002_add_to_field_to_processreport'),
    ]

    operations = [
        # Chuẩn hoá dữ liệu cũ: đổi '' (chuỗi rỗng) thành '0' trước khi
        # MySQL chuyển kiểu cột từ VARCHAR sang INT (tránh lỗi 1366)
        migrations.RunSQL(
            sql="UPDATE working_processreport SET `to` = '0' WHERE `to` = '' OR `to` IS NULL;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='processreport',
            name='to',
            field=models.PositiveIntegerField(default=0, verbose_name='Tổ'),
        ),
    ]
