# Generated by Django 6.0.6 on 2026-08-03 15:08

from django.db import migrations, models


def convert_to_field_to_zero(apps, schema_editor):
    ProcessReport = apps.get_model('Working', 'ProcessReport')
    # Cập nhật các bản ghi có `to` là chuỗi rỗng hoặc NULL thành '0'
    ProcessReport.objects.filter(to='').update(to='0')
    ProcessReport.objects.filter(to__isnull=True).update(to='0')


class Migration(migrations.Migration):

    dependencies = [
        ('Working', '0002_add_to_field_to_processreport'),
    ]

    operations = [
        # Chuẩn hoá dữ liệu cũ bằng ORM thay vì SQL thuần để tránh lỗi sai tên bảng
        # do phân biệt hoa/thường trên các hệ điều hành khác nhau
        migrations.RunPython(
            convert_to_field_to_zero,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='processreport',
            name='to',
            field=models.PositiveIntegerField(default=0, verbose_name='Tổ'),
        ),
    ]
