# Generated by Django 6.0.6 on 2026-08-09 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Working', '0003_change_to_field_to_positiveinteger'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='role',
            field=models.CharField(choices=[('BASIC', 'Cơ bản'), ('PREMIUM', 'Cao cấp')], default='BASIC', max_length=20, verbose_name='Quyền hạn'),
        ),
    ]
