# Generated by Django 6.0.6 on 2026-08-09 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Working', '0004_appuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Đã duyệt'),
        ),
    ]
