# Generated by Django 6.0.6 on 2026-08-09 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Working', '0005_appuser_is_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Mã hàng')),
            ],
            options={
                'verbose_name': 'Mã hàng',
                'verbose_name_plural': 'Mã hàng',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Màu sắc')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='Working.product', verbose_name='Mã hàng')),
            ],
            options={
                'verbose_name': 'Màu sắc',
                'verbose_name_plural': 'Màu sắc',
                'ordering': ['name'],
                'unique_together': {('product', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Cỡ')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='Working.productcolor', verbose_name='Màu sắc')),
            ],
            options={
                'verbose_name': 'Cỡ',
                'verbose_name_plural': 'Cỡ',
                'ordering': ['name'],
                'unique_together': {('color', 'name')},
            },
        ),
    ]
