# Generated by Django 6.0.6 on 2026-08-09 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Working', '0006_product_productcolor_productsize'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcolor',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Tổng số lượng'),
        ),
    ]
