# Generated by Django 6.0.6 on 2026-08-09 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Working', '0007_productcolor_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='role',
            field=models.CharField(choices=[('BASIC', 'Cơ bản (Sản xuất)'), ('HOAN_THIEN', 'Hoàn thiện'), ('PREMIUM', 'Cao cấp (Admin)')], default='BASIC', max_length=20, verbose_name='Quyền hạn'),
        ),
        migrations.CreateModel(
            name='FinishingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_hang', models.CharField(max_length=255, verbose_name='Mã hàng')),
                ('mau', models.CharField(max_length=255, verbose_name='Màu')),
                ('nhan_hang_hoan_thien', models.PositiveIntegerField(default=0, verbose_name='Nhận hàng hoàn thiện')),
                ('the_bai', models.PositiveIntegerField(default=0, verbose_name='Thẻ bài')),
                ('gap_hang', models.PositiveIntegerField(default=0, verbose_name='Gấp hàng')),
                ('treo_dong_thung', models.PositiveIntegerField(default=0, verbose_name='Treo/Đóng thùng')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian nhập')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('nguoi_nhap', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finishing_reports', to='Working.appuser', verbose_name='Người nhập')),
            ],
            options={
                'verbose_name': 'Báo cáo hoàn thiện',
                'verbose_name_plural': 'Báo cáo hoàn thiện',
                'ordering': ['-created_at'],
            },
        ),
    ]
