# Generated by Django 6.0.6 on 2026-08-09 16:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Working', '0008_alter_appuser_role_finishingreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='finishingreport',
            name='ngay_lam_viec',
            field=models.DateField(default=datetime.date.today, verbose_name='Ngày làm việc'),
        ),
    ]
