# Generated by Django 6.0.6 on 2026-08-09 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Working', '0009_finishingreport_ngay_lam_viec'),
    ]

    operations = [
        migrations.AddField(
            model_name='finishingreport',
            name='size',
            field=models.CharField(default='N/A', max_length=50, verbose_name='Cỡ'),
        ),
    ]
