# Generated by Django 6.0.6 on 2026-08-09 17:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Working', '0010_finishingreport_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='processreport',
            name='ngay_lam_viec',
            field=models.DateField(default=datetime.date.today, verbose_name='Ngày làm việc'),
        ),
        migrations.AddField(
            model_name='processreport',
            name='xuong',
            field=models.PositiveIntegerField(default=1, verbose_name='Xưởng'),
        ),
    ]
