# Generated by Django 6.0.6 on 2026-08-09 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Working', '0011_processreport_ngay_lam_viec_processreport_xuong'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processreport',
            name='xuong',
            field=models.PositiveIntegerField(default=0, verbose_name='Xưởng'),
        ),
    ]
