# Generated by Django 6.0.6 on 2026-08-10 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Working', '0012_alter_processreport_xuong'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='role',
            field=models.CharField(choices=[('BASIC', 'Sản xuất'), ('HOAN_THIEN', 'Hoàn thiện'), ('QUAN_LY', 'Quản lý'), ('PREMIUM', 'Cao cấp (Admin)')], default='BASIC', max_length=20, verbose_name='Quyền hạn'),
        ),
    ]
