# Generated by Django 6.0.6 on 2026-08-11 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Working', '0013_alter_appuser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finishingreport',
            name='nhan_hang_hoan_thien',
        ),
    ]
