# Generated by Django 6.0.6 on 2026-08-11 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Working', '0014_remove_finishingreport_nhan_hang_hoan_thien'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processreport',
            name='kcs',
        ),
    ]
