# Generated by Django 6.0.6 on 2026-08-11 16:33

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Working', '0015_remove_processreport_kcs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='role',
            field=models.CharField(choices=[('BASIC', 'Sản xuất'), ('HOAN_THIEN', 'Hoàn thiện'), ('KCS', 'KCS'), ('QUAN_LY', 'Quản lý'), ('PREMIUM', 'Cao cấp (Admin)')], default='BASIC', max_length=20, verbose_name='Quyền hạn'),
        ),
        migrations.CreateModel(
            name='KcsReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_lam_viec', models.DateField(default=datetime.date.today, verbose_name='Ngày làm việc')),
                ('xuong', models.PositiveIntegerField(default=0, verbose_name='Xưởng')),
                ('to', models.PositiveIntegerField(default=0, verbose_name='Tổ')),
                ('ma_hang', models.CharField(max_length=255, verbose_name='Mã hàng')),
                ('mau', models.CharField(max_length=255, verbose_name='Màu')),
                ('size', models.CharField(default='N/A', max_length=50, verbose_name='Cỡ')),
                ('qua_tay', models.PositiveIntegerField(default=0, verbose_name='Qua tay')),
                ('dat', models.PositiveIntegerField(default=0, verbose_name='Đạt')),
                ('loi', models.PositiveIntegerField(default=0, verbose_name='Lỗi')),
                ('tong_dat', models.PositiveIntegerField(default=0, verbose_name='Tổng đạt')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian nhập')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('nguoi_nhap', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kcs_reports', to='Working.appuser', verbose_name='Người nhập')),
            ],
            options={
                'verbose_name': 'Báo cáo KCS',
                'verbose_name_plural': 'Báo cáo KCS',
                'ordering': ['-created_at'],
            },
        ),
    ]
