# Generated by Django 6.0.6 on 2026-08-12 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Working', '0017_alter_appuser_role_cutreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='processreport',
            name='so_luong_ld',
            field=models.PositiveIntegerField(default=0, verbose_name='Số lượng LĐ'),
        ),
    ]
