# Generated by Django 6.0.6 on 2026-08-17 16:15

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Working', '0018_processreport_so_luong_ld'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefectReturnReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_tra', models.DateField(default=datetime.date.today, verbose_name='Ngày trả')),
                ('ma_hang', models.CharField(max_length=255, verbose_name='Mã hàng')),
                ('mau', models.CharField(max_length=255, verbose_name='Màu')),
                ('xuong', models.PositiveIntegerField(default=0, verbose_name='Xưởng')),
                ('to', models.PositiveIntegerField(default=0, verbose_name='Tổ')),
                ('so_luong_tra', models.PositiveIntegerField(default=0, verbose_name='Số lượng trả')),
                ('so_luong_nhan_lai', models.PositiveIntegerField(default=0, verbose_name='Số lượng nhận lại')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian nhập')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('nguoi_nhap', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='defect_return_reports', to='Working.appuser', verbose_name='Người nhập')),
            ],
            options={
                'verbose_name': 'Báo cáo trả hàng lỗi',
                'verbose_name_plural': 'Báo cáo trả hàng lỗi',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SampleTakeReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_lay', models.DateField(default=datetime.date.today, verbose_name='Ngày lấy')),
                ('ma_hang', models.CharField(max_length=255, verbose_name='Mã hàng')),
                ('mau', models.CharField(max_length=255, verbose_name='Màu')),
                ('nguoi_lay', models.CharField(default='', max_length=255, verbose_name='Người lấy')),
                ('so_luong_lay', models.PositiveIntegerField(default=0, verbose_name='Số lượng lấy')),
                ('so_luong_nhan_lai', models.PositiveIntegerField(default=0, verbose_name='Số lượng nhận lại')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian nhập')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('nguoi_nhap', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sample_take_reports', to='Working.appuser', verbose_name='Người nhập')),
            ],
            options={
                'verbose_name': 'Báo cáo lấy mẫu',
                'verbose_name_plural': 'Báo cáo lấy mẫu',
                'ordering': ['-created_at'],
            },
        ),
    ]
