# Generated by Django 6.0.6 on 2026-08-17 16:34

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Working', '0019_defectreturnreport_sampletakereport'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefectReceiveLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_nhan', models.DateField(default=datetime.date.today, verbose_name='Ngày nhận lại')),
                ('so_luong', models.PositiveIntegerField(default=0, verbose_name='Số lượng nhận lại')),
                ('ghi_chu', models.CharField(blank=True, default='', max_length=255, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian ghi nhận')),
                ('nguoi_nhap', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='defect_receive_logs', to='Working.appuser', verbose_name='Người ghi nhận')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receive_logs', to='Working.defectreturnreport', verbose_name='Phiếu trả lỗi')),
            ],
            options={
                'verbose_name': 'Lịch sử nhận lại hàng lỗi',
                'verbose_name_plural': 'Lịch sử nhận lại hàng lỗi',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SampleReceiveLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_nhan', models.DateField(default=datetime.date.today, verbose_name='Ngày nhận lại')),
                ('so_luong', models.PositiveIntegerField(default=0, verbose_name='Số lượng nhận lại')),
                ('ghi_chu', models.CharField(blank=True, default='', max_length=255, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian ghi nhận')),
                ('nguoi_nhap', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sample_receive_logs', to='Working.appuser', verbose_name='Người ghi nhận')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receive_logs', to='Working.sampletakereport', verbose_name='Phiếu lấy mẫu')),
            ],
            options={
                'verbose_name': 'Lịch sử nhận lại hàng mẫu',
                'verbose_name_plural': 'Lịch sử nhận lại hàng mẫu',
                'ordering': ['-created_at'],
            },
        ),
    ]
