# Generated by Django 6.0.6 on 2026-08-18 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Working', '0021_alter_appuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='role',
            field=models.CharField(choices=[('BASIC', 'Sản xuất'), ('HOAN_THIEN', 'Hoàn thiện'), ('KCS', 'KCS'), ('NHA_CAT', 'Nhà cắt'), ('KHO', 'Kho'), ('KE_TOAN', 'Kế toán'), ('QUAN_LY', 'Quản lý'), ('PREMIUM', 'Cao cấp (Admin)')], default='BASIC', max_length=20, verbose_name='Quyền hạn'),
        ),
    ]
