# Generated by Django 6.0.6 on 2026-08-17 17:11

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Working', '0021_alter_appuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_xuat', models.DateField(default=datetime.date.today, verbose_name='Ngày xuất hàng')),
                ('ma_hang', models.CharField(max_length=255, verbose_name='Mã hàng')),
                ('mau', models.CharField(max_length=255, verbose_name='Màu sắc')),
                ('so_luong_xuat', models.PositiveIntegerField(default=0, verbose_name='Số lượng xuất')),
                ('don_gia', models.PositiveBigIntegerField(default=0, verbose_name='Đơn giá tại thời điểm xuất (VNĐ)')),
                ('thanh_tien', models.PositiveBigIntegerField(default=0, verbose_name='Thành tiền (VNĐ)')),
                ('ghi_chu', models.CharField(blank=True, default='', max_length=500, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('nguoi_nhap', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='export_reports', to='Working.appuser', verbose_name='Người nhập')),
            ],
            options={
                'verbose_name': 'Phiếu xuất hàng',
                'verbose_name_plural': 'Phiếu xuất hàng',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('don_gia', models.PositiveBigIntegerField(default=0, verbose_name='Đơn giá (VNĐ)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('product_color', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='price', to='Working.productcolor', verbose_name='Mã & Màu sản phẩm')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_prices', to='Working.appuser', verbose_name='Người cập nhật')),
            ],
            options={
                'verbose_name': 'Đơn giá sản phẩm',
                'verbose_name_plural': 'Đơn giá sản phẩm',
                'ordering': ['product_color__product__name', 'product_color__name'],
            },
        ),
    ]
