# Generated by Django 6.0.6 on 2026-08-25 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productprice',
            options={'ordering': ['product_color__product__name', 'product_color__name'], 'verbose_name': 'Đơn giá & Giá CM sản phẩm', 'verbose_name_plural': 'Đơn giá & Giá CM sản phẩm'},
        ),
        migrations.AddField(
            model_name='productprice',
            name='gia_cm',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Giá CM (VNĐ)'),
        ),
    ]
