# Generated by Django 6.0.6 on 2026-08-25 15:16

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0002_alter_productprice_options_productprice_gia_cm'),
        ('Working', '0022_alter_appuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_thanh_toan', models.DateField(default=datetime.date.today, verbose_name='Ngày thanh toán')),
                ('so_tien', models.PositiveBigIntegerField(default=0, verbose_name='Số tiền đã thanh toán (VNĐ)')),
                ('ghi_chu', models.CharField(blank=True, default='', max_length=500, verbose_name='Ghi chú / Chứng từ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('nguoi_nhap', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_reports', to='Working.appuser', verbose_name='Người nhập')),
                ('product_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='Working.productcolor', verbose_name='Mã hàng & Màu sắc')),
            ],
            options={
                'verbose_name': 'Phiếu thanh toán',
                'verbose_name_plural': 'Phiếu thanh toán',
                'ordering': ['-created_at'],
            },
        ),
    ]
